#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
#
# install-to-sdcard.sh -- drop a Zephyr build onto a PINN-imaged
# Raspberry Pi Zero 2 W microSD card.
#
# Targets a PINN recovery partition (mounted at /Volumes/RECOVERY on
# macOS by default) rather than a vanilla Raspberry Pi OS bootfs.
#
# Usage:
#   install-to-sdcard.sh [<recovery-mount-point>] <path-to-zephyr.bin>
#
# Examples:
#   # macOS, PINN-imaged card auto-mounts at /Volumes/RECOVERY:
#   ./install-to-sdcard.sh ~/Downloads/zephyr.bin
#
#   # Explicit mount point:
#   ./install-to-sdcard.sh /Volumes/RECOVERY ~/Downloads/zephyr.bin
#
#   # Linux:
#   ./install-to-sdcard.sh /media/$USER/RECOVERY ~/Downloads/zephyr.bin
#
# The script:
#   1. Copies zephyr.bin into the recovery partition.
#   2. Replaces config.txt with the rpi_zero_2w boot params
#      (mini-UART fallback console @ 115200, 64-bit kernel at
#      0x200000), preserving the original as config.txt.orig on
#      first run. The primary console is USB-CDC ACM, configured
#      inside the Zephyr image itself.
#
# Pi firmware blobs (bootcode.bin, fixup.dat, start.elf) stay untouched.

set -e

# Default mount point if only one arg given. Override by passing two.
DEFAULT_MOUNT="/Volumes/RECOVERY"

case $# in
1)
	MOUNT="$DEFAULT_MOUNT"
	ZEPHYR_BIN="$1"
	;;
2)
	MOUNT="$1"
	ZEPHYR_BIN="$2"
	;;
*)
	cat >&2 <<EOF
Usage: $0 [<recovery-mount-point>] <path-to-zephyr.bin>

If <recovery-mount-point> is omitted it defaults to $DEFAULT_MOUNT
(the macOS auto-mount path for a PINN-imaged Pi SD card).
EOF
	exit 1
	;;
esac

if [ ! -d "$MOUNT" ]; then
	echo "error: $MOUNT is not a directory (is the SD card mounted?)" >&2
	exit 1
fi
if [ ! -f "$ZEPHYR_BIN" ]; then
	echo "error: $ZEPHYR_BIN: file not found" >&2
	exit 1
fi
if [ ! -f "$MOUNT/bootcode.bin" ] || [ ! -f "$MOUNT/start.elf" ]; then
	echo "error: $MOUNT does not look like a Pi boot partition" >&2
	echo "       (no bootcode.bin or start.elf present)" >&2
	echo "       Make sure the SD card is PINN-imaged." >&2
	exit 1
fi

cp "$ZEPHYR_BIN" "$MOUNT/zephyr.bin"

if [ -f "$MOUNT/config.txt" ] && [ ! -f "$MOUNT/config.txt.orig" ]; then
	cp "$MOUNT/config.txt" "$MOUNT/config.txt.orig"
fi

cat > "$MOUNT/config.txt" <<'EOF'
# Generated by jetpax/PiZZa::install-to-sdcard.sh.
# The previous config.txt is preserved as config.txt.orig.

arm_64bit=1

# Mini-UART (uart1) on GPIO 14/15 at 115200 baud is the safe default
# console: every USB-serial adapter handles it, and start.elf does
# nothing special with the UART_CLK. Use this as a fallback if the
# image's primary USB-CDC console doesn't enumerate on your host.
#
# enable_uart=1 also locks the core clock at 250 MHz so the mini-UART
# integer baud divisor stays valid across CPU frequency changes.
enable_uart=1
core_freq=250

kernel_address=0x200000
kernel=zephyr.bin
EOF

echo "Installed $(basename "$ZEPHYR_BIN") to $MOUNT."
echo "Eject the card and boot the Pi:"
echo
case "$(uname -s)" in
Darwin)
	echo "  diskutil eject \"$MOUNT\""
	;;
Linux)
	echo "  udisksctl unmount -b \"\$(findmnt -no SOURCE \"$MOUNT\")\""
	;;
*)
	echo "  (eject the card via your OS's usual mechanism)"
	;;
esac
