#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
#
# install-to-sdcard.sh -- drop a Zephyr build onto a PINN-imaged
# Raspberry Pi Zero 2 W microSD card.
#
# Targets a PINN recovery partition (mounted at /Volumes/RECOVERY on
# macOS by default) rather than a vanilla Raspberry Pi OS bootfs.
#
# Usage:
#   install-to-sdcard.sh [<recovery-mount-point>] <path-to-zephyr.bin>
#
# Examples:
#   # macOS, PINN-imaged card auto-mounts at /Volumes/RECOVERY:
#   ./install-to-sdcard.sh ~/Downloads/zephyr.bin
#
#   # Explicit mount point:
#   ./install-to-sdcard.sh /Volumes/RECOVERY ~/Downloads/zephyr.bin
#
#   # Linux:
#   ./install-to-sdcard.sh /media/$USER/RECOVERY ~/Downloads/zephyr.bin
#
# The script:
#   1. Copies zephyr.bin into the recovery partition.
#   2. Replaces config.txt with the rpi_zero_2w boot params (PL011
#      console on GPIO 14/15 at 1 Mbaud), preserving the original as
#      config.txt.orig on first run.
#
# Pi firmware blobs (bootcode.bin, fixup.dat, start.elf) stay untouched.

set -e

# Default mount point if only one arg given. Override by passing two.
DEFAULT_MOUNT="/Volumes/RECOVERY"

case $# in
1)
	MOUNT="$DEFAULT_MOUNT"
	ZEPHYR_BIN="$1"
	;;
2)
	MOUNT="$1"
	ZEPHYR_BIN="$2"
	;;
*)
	cat >&2 <<EOF
Usage: $0 [<recovery-mount-point>] <path-to-zephyr.bin>

If <recovery-mount-point> is omitted it defaults to $DEFAULT_MOUNT
(the macOS auto-mount path for a PINN-imaged Pi SD card).
EOF
	exit 1
	;;
esac

if [ ! -d "$MOUNT" ]; then
	echo "error: $MOUNT is not a directory (is the SD card mounted?)" >&2
	exit 1
fi
if [ ! -f "$ZEPHYR_BIN" ]; then
	echo "error: $ZEPHYR_BIN: file not found" >&2
	exit 1
fi
if [ ! -f "$MOUNT/bootcode.bin" ] || [ ! -f "$MOUNT/start.elf" ]; then
	echo "error: $MOUNT does not look like a Pi boot partition" >&2
	echo "       (no bootcode.bin or start.elf present)" >&2
	echo "       Make sure the SD card is PINN-imaged." >&2
	exit 1
fi

cp "$ZEPHYR_BIN" "$MOUNT/zephyr.bin"

if [ -f "$MOUNT/config.txt" ] && [ ! -f "$MOUNT/config.txt.orig" ]; then
	cp "$MOUNT/config.txt" "$MOUNT/config.txt.orig"
fi

cat > "$MOUNT/config.txt" <<'EOF'
# Generated by jetpax/PiZZa::install-to-sdcard.sh.
# The previous config.txt is preserved as config.txt.orig.

arm_64bit=1
core_freq=250

# Route the PL011 (uart0) to GPIO 14/15 by moving Bluetooth onto the
# mini-UART. The PL011 has a 16+6-bit fractional baud divider, far
# more flexible than the mini-UART's integer-only divisor.
enable_uart=1
dtoverlay=disable-bt

# 1 Mbaud lands on an exact integer divisor at the default 48 MHz
# PL011 UART_CLK (IBRD=3, FBRD=0 -> 48 MHz / 16 / 3 = 1 MHz exactly).
init_uart_baud=1000000

kernel_address=0x200000
kernel=zephyr.bin
EOF

echo "Installed $(basename "$ZEPHYR_BIN") to $MOUNT."
echo "Eject the card and boot the Pi:"
echo
case "$(uname -s)" in
Darwin)
	echo "  diskutil eject \"$MOUNT\""
	;;
Linux)
	echo "  udisksctl unmount -b \"\$(findmnt -no SOURCE \"$MOUNT\")\""
	;;
*)
	echo "  (eject the card via your OS's usual mechanism)"
	;;
esac
