#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
#
# install-to-sdcard.sh -- drop a Zephyr build onto a PiZZa-imaged
# microSD card (see make-sdcard.sh to create one).
#
# Usage:
#   install-to-sdcard.sh [rpi_zero_2w|rpi_zero_w] [<boot-partition-mount>] <path-to-zephyr.bin>
#
# The board defaults to rpi_zero_2w. THE BOARDS ARE NOT INTERCHANGEABLE:
# the Zero 2 W boots a 64-bit kernel at 0x200000, the original Zero W a
# 32-bit kernel at 0x8000 -- installing with the wrong board writes a
# config.txt the kernel can't boot from (no console, no enumeration).
#
# Examples:
#   # macOS, PiZZa card auto-mounts at /Volumes/PIZZA:
#   ./install-to-sdcard.sh ~/Downloads/zephyr.bin
#
#   # Original Pi Zero W:
#   ./install-to-sdcard.sh rpi_zero_w ~/Downloads/zephyr.bin
#
#   # Explicit mount point:
#   ./install-to-sdcard.sh /Volumes/PIZZA ~/Downloads/zephyr.bin
#
#   # Linux:
#   ./install-to-sdcard.sh /media/$USER/PIZZA ~/Downloads/zephyr.bin
#
# The script:
#   1. Copies zephyr.bin into the boot partition.
#   2. Replaces config.txt with the board's boot params (from the
#      repo's config.txt / config-rpi_zero_w.txt), preserving the
#      original as config.txt.orig on first run.
#
# Pi firmware blobs (bootcode.bin, fixup.dat, start.elf) stay untouched.

set -e

HERE=$(cd "$(dirname "$0")" && pwd)

# Optional board selector as the first argument.
BOARD="rpi_zero_2w"
case "${1:-}" in
rpi_zero_2w|rpi_zero_w)
	BOARD="$1"
	shift
	;;
esac
case "$BOARD" in
rpi_zero_2w) CONFIG_SRC="$HERE/config.txt" ;;
rpi_zero_w)  CONFIG_SRC="$HERE/config-rpi_zero_w.txt" ;;
esac

# Default mount point if only one arg given (first existing candidate
# wins -- PIZZA is the make-sdcard.sh volume label, RECOVERY covers
# cards imaged before July 2026). Override by passing two args.
DEFAULT_MOUNT="/Volumes/PIZZA"
[ -d "$DEFAULT_MOUNT" ] || { [ -d /Volumes/RECOVERY ] && DEFAULT_MOUNT="/Volumes/RECOVERY"; } || true

case $# in
1)
	MOUNT="$DEFAULT_MOUNT"
	ZEPHYR_BIN="$1"
	;;
2)
	MOUNT="$1"
	ZEPHYR_BIN="$2"
	;;
*)
	cat >&2 <<EOF
Usage: $0 [<recovery-mount-point>] <path-to-zephyr.bin>

If <boot-partition-mount> is omitted it defaults to $DEFAULT_MOUNT
(the macOS auto-mount path for a PiZZa-imaged SD card).
EOF
	exit 1
	;;
esac

if [ ! -d "$MOUNT" ]; then
	echo "error: $MOUNT is not a directory (is the SD card mounted?)" >&2
	exit 1
fi
if [ ! -f "$ZEPHYR_BIN" ]; then
	echo "error: $ZEPHYR_BIN: file not found" >&2
	exit 1
fi
if [ ! -f "$MOUNT/bootcode.bin" ] || [ ! -f "$MOUNT/start.elf" ]; then
	echo "error: $MOUNT does not look like a Pi boot partition" >&2
	echo "       (no bootcode.bin or start.elf present)" >&2
	echo "       Flash a PiZZa image first -- see make-sdcard.sh / Releases." >&2
	exit 1
fi

cp "$ZEPHYR_BIN" "$MOUNT/zephyr.bin"

if [ -f "$MOUNT/config.txt" ] && [ ! -f "$MOUNT/config.txt.orig" ]; then
	cp "$MOUNT/config.txt" "$MOUNT/config.txt.orig"
fi

{
	echo "# Generated by jetpax/PiZZa::install-to-sdcard.sh ($BOARD)."
	echo "# The previous config.txt is preserved as config.txt.orig."
	echo
	cat "$CONFIG_SRC"
} > "$MOUNT/config.txt"

echo "Installed $(basename "$ZEPHYR_BIN") to $MOUNT ($BOARD config)."
echo "Eject the card and boot the Pi:"
echo
case "$(uname -s)" in
Darwin)
	echo "  diskutil eject \"$MOUNT\""
	;;
Linux)
	echo "  udisksctl unmount -b \"\$(findmnt -no SOURCE \"$MOUNT\")\""
	;;
*)
	echo "  (eject the card via your OS's usual mechanism)"
	;;
esac
