#!/bin/sh
# stage-os.sh -- deposit PiZZaBoot's PINN OS folders onto a PINN-imaged
# Raspberry Pi Zero 2 W SD card. Host-side; pure file copy + tar.xz build.
#
# Run AFTER imaging the card with PINN (Raspberry Pi Imager → Misc utility
# images → PINN). The card's RECOVERY partition must be mounted (macOS
# auto-mounts at /Volumes/RECOVERY).
#
# What this script does:
#   1. Reads each PiZZa/apps/<NAME>/ folder.
#   2. Builds <label>.tar.xz from the OS's binary + GPU blobs from the
#      mounted RECOVERY + (for ScriptoStudio) the device-scripts payload.
#   3. Copies os.json, partitions.json, partition_setup.sh, and the
#      tarball into <RECOVERY>/os/<NAME>/.
#   4. Adds `silentinstall` to <RECOVERY>/cmdline.txt so the headless
#      install runs on next boot.
#
# Eject the card after this script finishes; PINN's silentinstall does
# the rest unattended.
#
# Usage:
#   ./stage-os.sh                              # default mount + bin paths
#   ./stage-os.sh /Volumes/RECOVERY            # explicit mount
#   STAGE_DIR=/tmp/sdimg ./stage-os.sh         # stage to a dir (testing)
#
# Override via env vars:
#   STAGE_DIR             where to write (defaults to first CLI arg or
#                         /Volumes/RECOVERY)
#   PIZZABOOT_BIN         path to PiZZaBoot manager zephyr.bin
#   SCRIPTOSTUDIO_BIN     path to ScriptoStudio (mpy-wbp+ulab) zephyr.bin
#   DEVICE_SCRIPTS_DIR    path to device-scripts/ tree

set -e

# --- Paths ---
REPO="$(cd "$(dirname "$0")" && pwd)"
STAGE_DIR="${STAGE_DIR:-${1:-/Volumes/RECOVERY}}"

PIZZABOOT_BIN="${PIZZABOOT_BIN:-$HOME/zephyrproject/build/pizzaboot/zephyr/zephyr.bin}"
SCRIPTOSTUDIO_BIN="${SCRIPTOSTUDIO_BIN:-$HOME/zephyrproject/build/mpy-rpi_zero_2w-ulab/zephyr/zephyr.bin}"
DEVICE_SCRIPTS_DIR="${DEVICE_SCRIPTS_DIR:-$HOME/github/SS/scriptostudio/boards/firmware/device-scripts}"

# --- Colors (only if stdout is a tty) ---
if [ -t 1 ]; then
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    RED='\033[0;31m'
    NC='\033[0m'
else
    GREEN=''; YELLOW=''; RED=''; NC=''
fi

die() { printf "${RED}error:${NC} %s\n" "$*" >&2; exit 1; }
note() { printf "${GREEN}%s${NC}\n" "$*"; }
warn() { printf "${YELLOW}%s${NC}\n" "$*"; }

# --- Validate ---
[ -d "$STAGE_DIR" ] || die "STAGE_DIR not a directory: $STAGE_DIR (is the SD card mounted?)"

# A real PINN card has these in the root of RECOVERY. Skip the check when
# staging to a non-mounted scratch dir.
if [ -e "$STAGE_DIR/bootcode.bin" ]; then
    BLOB_SRC="$STAGE_DIR"
else
    warn "$STAGE_DIR has no bootcode.bin; tarballs will be built without GPU blobs."
    warn "  (OK for layout-validation testing; not OK for a real card.)"
    BLOB_SRC=""
fi

[ -f "$PIZZABOOT_BIN" ] || die "PIZZABOOT_BIN not found: $PIZZABOOT_BIN"
[ -f "$SCRIPTOSTUDIO_BIN" ] || die "SCRIPTOSTUDIO_BIN not found: $SCRIPTOSTUDIO_BIN"
[ -d "$DEVICE_SCRIPTS_DIR" ] || die "DEVICE_SCRIPTS_DIR not found: $DEVICE_SCRIPTS_DIR"

note "Staging into $STAGE_DIR"
note "  PiZZaBoot binary:    $PIZZABOOT_BIN"
note "  ScriptoStudio binary: $SCRIPTOSTUDIO_BIN"
note "  device-scripts/ tree: $DEVICE_SCRIPTS_DIR"
[ -n "$BLOB_SRC" ] && note "  GPU blobs:           $BLOB_SRC/{bootcode.bin,start*.elf,fixup*.dat}"
echo ""

# --- Helpers ---

# Copy GPU blobs into the staging tree. Anything matching the Pi 3 family
# blob set (bootcode.bin, fixup*.dat, start*.elf) is included.
copy_blobs() {
    target="$1"
    [ -z "$BLOB_SRC" ] && return 0
    for pattern in 'bootcode.bin' 'fixup*.dat' 'start*.elf'; do
        for blob in "$BLOB_SRC"/$pattern; do
            [ -f "$blob" ] || continue
            cp "$blob" "$target/"
        done
    done
}

# Build a tarball. Args: <source dir> <output .tar.xz>. Excludes the
# usual mac / python toolchain droppings.
build_tarball() {
    src="$1"; out="$2"
    rm -f "$out"
    (cd "$src" && tar --format=ustar \
        --exclude='.DS_Store' \
        --exclude='__pycache__' \
        --exclude='*.pyc' \
        -cf - .) | xz -9 > "$out"
}

# Render the shared Pi boot config.txt into a target dir. Same body the
# existing install-to-sdcard.sh writes, kept consistent here.
write_config_txt() {
    target="$1"
    cat > "$target/config.txt" <<'EOF'
# Generated by jetpax/PiZZa::stage-os.sh.

arm_64bit=1
# enable_uart=1 routes the mini-UART to GPIO 14/15 and locks the core
# clock so its baud divisor stays valid.
enable_uart=1
core_freq=250
kernel_address=0x200000
kernel=zephyr.bin
EOF
}

# --- Stage PiZZaBoot ---
stage_pizzaboot() {
    note "[1/2] PiZZaBoot"
    src="$REPO/apps/PiZZaBoot"
    dst="$STAGE_DIR/os/PiZZaBoot"
    mkdir -p "$dst"

    # Metadata + setup script
    cp "$src/os.json" "$dst/"
    cp "$src/partitions.json" "$dst/"
    cp "$src/partition_setup.sh" "$dst/"
    chmod +x "$dst/partition_setup.sh"

    # Build tarball
    workdir=$(mktemp -d)
    cp "$PIZZABOOT_BIN" "$workdir/zephyr.bin"
    write_config_txt "$workdir"
    copy_blobs "$workdir"

    build_tarball "$workdir" "$dst/pizzaboot.tar.xz"

    SIZE=$(ls -l "$dst/pizzaboot.tar.xz" | awk '{print $5}')
    note "  -> $dst/pizzaboot.tar.xz ($SIZE bytes)"
    rm -rf "$workdir"
}

# --- Stage ScriptoStudio ---
stage_scriptostudio() {
    note "[2/2] ScriptoStudio"
    src="$REPO/apps/ScriptoStudio"
    dst="$STAGE_DIR/os/ScriptoStudio"
    mkdir -p "$dst"

    cp "$src/os.json" "$dst/"
    cp "$src/partitions.json" "$dst/"

    # Build firmware tarball (gets extracted into the scriptostudio partition).
    workdir=$(mktemp -d)
    cp "$SCRIPTOSTUDIO_BIN" "$workdir/zephyr.bin"
    write_config_txt "$workdir"
    copy_blobs "$workdir"
    # Drop the device-scripts payload at the root of the partition --
    # boot.py, main.py, lib/, settings/, demo/.
    (cd "$DEVICE_SCRIPTS_DIR" && tar -cf - .) | (cd "$workdir" && tar -xf -)

    build_tarball "$workdir" "$dst/scriptostudio.tar.xz"

    SIZE=$(ls -l "$dst/scriptostudio.tar.xz" | awk '{print $5}')
    note "  -> $dst/scriptostudio.tar.xz ($SIZE bytes)"
    # scriptostudio_sd partition is empty_fs:true; no tarball needed.
    rm -rf "$workdir"
}

# --- Add silentinstall to PINN's boot cmdline ---
add_silentinstall() {
    cmdline="$STAGE_DIR/cmdline.txt"
    if [ ! -f "$cmdline" ]; then
        warn "no cmdline.txt at $cmdline; silentinstall not added"
        return 0
    fi
    if grep -q silentinstall "$cmdline"; then
        note "silentinstall already present in $cmdline"
        return 0
    fi
    # Preserve original on first edit.
    [ -f "${cmdline}.orig" ] || cp "$cmdline" "${cmdline}.orig"
    # PINN's cmdline.txt is one line. Append our flag.
    sed -i.bak -e '$ s/$/ silentinstall/' "$cmdline"
    rm -f "${cmdline}.bak"
    note "Appended silentinstall to $cmdline"
}

# --- Run ---
stage_pizzaboot
stage_scriptostudio
add_silentinstall

echo ""
note "Done."
echo "Eject the card and boot the Pi:"
echo ""
case "$(uname -s)" in
Darwin)
    echo "  diskutil eject \"$STAGE_DIR\""
    ;;
Linux)
    echo "  udisksctl unmount -b \"\$(findmnt -no SOURCE \"$STAGE_DIR\")\""
    ;;
*)
    echo "  (eject the card via your OS)"
    ;;
esac
echo ""
echo "First boot will run PINN silentinstall (~1-2 min). The Pi reboots"
echo "into PiZZaBoot manager, which immediately chainboots ScriptoStudio."
