# SPDX-License-Identifier: Apache-2.0
#
# PiZZaBoot -- Tier-1 boot menu. Deliberately dumb: no shell, no
# networking, no BT. Menu on mini-UART + USB CDC + HDMI; boots fast.

CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=8192

CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

CONFIG_GPIO=y

CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_LFN_MODE_STACK=y

CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BACKEND_UART=y
