/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Fixed-ratio 44100 -> 48000 stereo S16 resampler -- freestanding C
 * (HDMI-audio work order §2, M0). Rational 147:160 polyphase FIR;
 * coefficient table generated by tools/gen_resample_coefs.py (Q15,
 * per-phase rows sum exactly 32768, so DC passes bit-exactly).
 *
 * Pull model: rs48_produce() emits exactly the requested number of
 * output frames and pulls however many input frames that takes
 * (amortized 147 in per 160 out) from the supplied source callback
 * in a single batched call.
 */

#ifndef PIZZA_RESAMPLE_48K_H
#define PIZZA_RESAMPLE_48K_H

#include <stdint.h>

#include "resample_48k_coefs.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Source callback: fill dst with `frames` frames of interleaved S16
 * stereo at 44.1 kHz.
 */
typedef void (*rs48_source_fn)(void *user, int16_t *dst,
			       unsigned int frames);

/* Upper bound on input frames consumed per rs48_produce() call of n
 * output frames: ceil(n * 147 / 160) + 1.
 */
#define RS48_MAX_PULL(out_frames) (((out_frames) * RS48_M) / RS48_L + 2)

struct rs48 {
	unsigned int phase;              /* 0..RS48_L; RS48_L = pull pending */
	int16_t hist[RS48_TAPS][2];      /* last TAPS input frames, [TAPS-1] newest */
};

void rs48_init(struct rs48 *rs);

/* Produce `out_frames` frames of interleaved S16 stereo at 48 kHz
 * into `out`. `out_frames` must be <= RS48_PRODUCE_MAX.
 */
#define RS48_PRODUCE_MAX 192

void rs48_produce(struct rs48 *rs, int16_t *out, unsigned int out_frames,
		  rs48_source_fn source, void *user);

#ifdef __cplusplus
}
#endif

#endif /* PIZZA_RESAMPLE_48K_H */
